# Generated by Django 5.2.5 on 2025-08-16 15:44

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a project image (max 5MB)",
                null=True,
                upload_to="project_images/",
                validators=[projects.models.validate_project_image_size],
            ),
        ),
    ]
