# Generated by Django 5.2.4 on 2025-07-31 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_developer_profile_picture_recruiter"),
        ("watchlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="developer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlisted_by",
                to="profiles.developer",
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="recruiter",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "recruiter"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlisted_developers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(
                fields=["recruiter", "saved_at"], name="watchlist_w_recruit_7cff45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(
                fields=["developer"], name="watchlist_w_develop_7e58b4_idx"
            ),
        ),
    ]
