# Generated by Django 5.2.5 on 2025-08-18 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "watchlist",
            "0002_alter_watchlist_developer_alter_watchlist_recruiter_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="recruiter",
            field=models.ForeignKey(
                limit_choices_to={"role": "recruiter"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlisted_developers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
