# Generated by Django 5.2.5 on 2025-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_developer_profile_picture_recruiter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="experience",
            field=models.IntegerField(default=0, help_text="Years of experience"),
        ),
    ]
