# Generated by Django 5.2.5 on 2025-08-14 15:32

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_developer_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture (max 5MB)",
                null=True,
                upload_to="profile_pictures/",
                validators=[profiles.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Upload your resume in PDF format (max 5 MB)",
                null=True,
                upload_to="resumes/",
                validators=[
                    profiles.models.validate_pdf_file,
                    profiles.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="video_intro",
            field=models.FileField(
                blank=True,
                help_text="Upload a video introduction (max 50MB)",
                null=True,
                upload_to="video_intros/",
                validators=[profiles.models.validate_video_size],
            ),
        ),
    ]
