# Generated by Django 5.2.5 on 2025-08-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_update_storage_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="developer",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="developer",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
