# Generated by Django 5.2.5 on 2025-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_developer_email_developer_linkedin_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="current_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="developer",
            name="current_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="developer",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="developer",
            name="emplyment_status",
            field=models.CharField(
                choices=[
                    ("employed", "Employed"),
                    ("unemployed", "Unemployed"),
                    ("freelancing", "Freelancing"),
                    ("student", "Student"),
                    ("other", "Other"),
                ],
                default="unemployed",
                max_length=50,
            ),
        ),
    ]
